#!/usr/bin/env bash
# Infinite loop that traps SIGTERM and prints invincible message before continuing indefinitely

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2 &  # run sleep in background
  wait        # allow bash to catch SIGTERM immediately
done
