#!/usr/bin/env bash
# Infinite loop printing phrase and echo invincible message on SIGTERM

# Set the SIGTERM handler once
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
