#!/usr/bin/env bash
# Infinite loop: prints phrase, traps SIGTERM to show invincible message and keep running

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
